<?xml version="1.0"?>
<package format="3">
  <name>iri_base_algorithm</name>
  <version>1.0.0</version>
  <description>Package for base algorithm of IRI robot.</description>

  <maintainer email="labrobotica@iri.upc.edu">labrobotica</maintainer>

  <license>LGPL</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>diagnostic_updater</depend>
   <!-- <depend>dynamic_reconfigure</depend>-->
  <depend>boost</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

