<?xml version="1.0"?>
<package format="3">
  <name>iri_laser_people_detection</name>
  <version>1.0.0</version>
  <description>
    Wrapper over laser_people_detection library to detect people using a single horizontal range laser sensor (default training using Hokuyo UTM-30LX at ~0.4m height)
  </description>

  <maintainer email="labrobotica@iri.upc.edu">IRI_labrobotica</maintainer>
  <license>LGPL</license>

  <author email="fherrero@iri.upc.edu">Fernando Herrero</author>

  <!-- Dependencies for building -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencies required to build and run -->
  <build_depend>iri_base_algorithm</build_depend>
  <build_depend>iri_perception_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>visualization_msgs</build_depend>
  <build_depend>tf2</build_depend>
  <build_depend>tf2_ros</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>rclcpp</build_depend>
  <build_depend>pluginlib</build_depend>

  <exec_depend>iri_base_algorithm</exec_depend>
  <exec_depend>iri_perception_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>tf2</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>pluginlib</exec_depend>
  
  <!-- Export tag for additional ROS 2-specific information -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
